services:
    client:
        image: spaces:latest
        build: ./
        container_name: spaces-clientspa
        ports:
            - '5173:5173'
        volumes:
            - '.:/app'
            - '/app/node_modules'
        stdin_open: true
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true
